---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# caRlo

<!-- badges: start -->
<!-- badges: end -->

The goal of caRlo is to sample, generate statistics, and plot outputs

## Installation

You can install the development version of caRlo from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("tgoodbody/caRlo")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r, echo = FALSE}
library(caRlo)
cores <- 5


data("plots")
data("samples")
data("stats")
data("bootstraps")

population <-  data.frame(median = 1.1, mean = 2.2)

```

```
#--- load internal data ---#

data("plots")
data("samples")
data("stats")

#--- fake population mean and median ---#
population <-  data.frame(median = 1.1, mean = 2.2)

#--- piped & parallel ---#

cores <- 5

monte_carlo(plots, nSamp = c(50, 100, 150), iter = 10, cores = cores) %>%
  stats_nested(cores = cores) %>%
  sample_bootstrap(., population = population, cores = cores)

#--- internal data for testing ---#
samples <- monte_carlo(data = plots, nSamp = c(50, 100, 150), iter = 3, cores = cores) 

nested <- stats_nested(data = samples, cores = cores)

bootstraps <- sample_bootstrap(data = stats, population = population, cores = cores)

#--- define functions for new stats ---#
```

## Specify user defined functions for statistics using `.f`
```{r}
#--- function needs to have more than 1 metric to give proper outputs ---#


.f <- function(x){

  #--- calculate the mean and percent of points less than the mean ---#
  c(mean = mean(x), 
  perc_gr_mean = length(x[x < mean(x)])/length(x))

} 

s <- stats_nested(data = samples, cores = cores, .f = .f)

s$statistics[[1]]

```

## outputs

```{r}
#--- using internal data ---#

monte_carlo(data = plots, nSamp = c(50, 100, 150), iter = 2, cores = cores) 

stats_nested(data = samples, cores = cores)

sample_bootstrap(data = stats, population = population, cores = cores)
```
